### ISSUE TITLE
Moving average of embedding

### ISSUE THREAD

**Issue by rahulvigneswaran** [KaihuaTang/Long-Tailed-Recognition.pytorch#14]
Why is there a moving average of the embedding out of the feature before it goes into the fully connected network?  What is it used for?
https://github.com/KaihuaTang/Long-Tailed-Recognition.pytorch/blob/540cae6da251f49b1b021630e219dde7c5867ce2/classification/run_networks.py#L215

**Comment by KaihuaTang** [comment]
Please refer to our paper: https://arxiv.org/abs/2009.12991
