### ISSUE TITLE
feat_uniform.yaml

### ISSUE THREAD

**Issue by rahulvigneswaran** [KaihuaTang/Long-Tailed-Recognition.pytorch#2]
1.  Is `feat_uniform.yaml` just normal training?
2.  For `ResNet32Feature.py`, why are you using the `BBN_ResNet_Cifar` class instead of using the parent class `ResNetFeature` ?

**Comment by KaihuaTang** [comment]
feat_uniform.yaml is part of original Decoupling code https://github.com/facebookresearch/classifier-balancing. We didn't run this stage. We only need to run causal_norm.yaml
