### ISSUE TITLE
ImageNet-LT

### ISSUE THREAD

**Issue by rahulvigneswaran** [KaihuaTang/Long-Tailed-Recognition.pytorch#4]
While using ImageNet-LT how to change between many-shot, medium-shot and few-shot ?

**Comment by KaihuaTang** [comment]
the evaluator will print “Many_shot_accuracy_top1”， “Median_shot_accuracy_top1”，  “Low_shot_accuracy_top1” at the same time. you don;t need to change anything.

**Comment by rahulvigneswaran** [comment]
okay, when you say Many-shot, median-shot, few-shot, they are only tested with those categories but the model is trained on all the classes?

**Comment by KaihuaTang** [comment]
yes
