### ISSUE TITLE
Regarding training_opt: {open_threshold: 0.1}

### ISSUE THREAD

**Issue by rahulvigneswaran** [KaihuaTang/Long-Tailed-Recognition.pytorch#6]
What does `training_opt: {open_threshold: 0.1}` do? It looks like, it is pointing to the `theta` below but it is not being used at all.
```
def F_measure(preds, labels, theta=None):
    # Regular f1 score
    return f1_score(labels.detach().cpu().numpy(), preds.detach().cpu().numpy(), average='macro')
```

**Comment by KaihuaTang** [comment]
I built my project on top of https://github.com/facebookresearch/classifier-balancing, which itself is built on top of https://github.com/zhmiao/OpenLongTailRecognition-OLTR

It's common to have some deprecated codes in the project. As long as, it doesn't cause any bug

**Comment by rahulvigneswaran** [comment]
@KaihuaTang Understood. Thanks alot.
